# Generated by Django 3.2 on 2024-03-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_images_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scraped_at',
        ),
    ]
