# Generated by Django 3.2 on 2024-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_scraped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
