# Generated by Django 3.2 on 2024-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calory_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
